
services: 
  mariadb:
    image: mariadb:latest
    container_name: mariadb_controller
    restart: always
    environment:
      TZ: Europe/Athens
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festival_database
      MYSQL_USER: user
      MYPASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer_controller
    restart: always
    ports:
      - 5050:8080      

  nodeapp:
    container_name: node_server
    build: ./Code
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb    
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: festival_database
    volumes:
      - ./Code:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
