version: '3.8'

services: 
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festival_database
      MYSQL_USER: user
      MYPASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer_controler
    restart: always
    ports:
      - 8080:8080      